version: 2
jobs:
  build:
    docker:
      - image: quay.io/cybozu/golang:1.10-bionic
      - image: quay.io/coreos/etcd:v3.3
    working_directory: /go/src/github.com/cybozu-go/sabakan
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: test -z "$(goimports -d . | tee /dev/stderr)"
      - run: golint -set_exit_status ./...
      - run: go build ./cmd/sabakan
      - run: go build ./cmd/sabactl
      - run:
          command: ./sabakan -dhcp-bind 0.0.0.0:10067 -etcd-servers http://localhost:2379
          background: true
      - run: go test -race -v ./...
